# coding: utf-8

"""
    Intersight REST API

    This is Intersight REST API 

    OpenAPI spec version: 1.0.9-961
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class WorkflowValidationInformation(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'state': 'str',
        'validation_error': 'list[WorkflowValidationError]'
    }

    attribute_map = {
        'state': 'State',
        'validation_error': 'ValidationError'
    }

    def __init__(self, state='NotValidated', validation_error=None):
        """
        WorkflowValidationInformation - a model defined in Swagger
        """

        self._state = None
        self._validation_error = None

        if state is not None:
          self.state = state
        if validation_error is not None:
          self.validation_error = validation_error

    @property
    def state(self):
        """
        Gets the state of this WorkflowValidationInformation.
        The current validation state of this workflow. The possible states are Valid, Invalid, NotValidated (default).  

        :return: The state of this WorkflowValidationInformation.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this WorkflowValidationInformation.
        The current validation state of this workflow. The possible states are Valid, Invalid, NotValidated (default).  

        :param state: The state of this WorkflowValidationInformation.
        :type: str
        """
        allowed_values = ["NotValidated", "Valid", "Invalid"]
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def validation_error(self):
        """
        Gets the validation_error of this WorkflowValidationInformation.
        List of all workflow or task validation errors. The validation errors can be for worker task or for control tasks.   

        :return: The validation_error of this WorkflowValidationInformation.
        :rtype: list[WorkflowValidationError]
        """
        return self._validation_error

    @validation_error.setter
    def validation_error(self, validation_error):
        """
        Sets the validation_error of this WorkflowValidationInformation.
        List of all workflow or task validation errors. The validation errors can be for worker task or for control tasks.   

        :param validation_error: The validation_error of this WorkflowValidationInformation.
        :type: list[WorkflowValidationError]
        """

        self._validation_error = validation_error

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, WorkflowValidationInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
