---

- hosts: ucs
  connection: local
  gather_facts: no
  vars:
    settings_file: settings.json
    # JSON for each host being claimed
    # ----------
    stash_json: ' { "hostname": "{{ hostname }}",
      "username": "{{ username }}",
      "password": "{{ password }}",
      "device_type": "{{ device_type }}"
      }'
  tasks:
  - name: Define proxy host and port if provided
    set_fact:
      stash_json: ' { "hostname": "{{ hostname }}",
        "username": "{{ username }}",
        "password": "{{ password }}",
        "device_type": "{{ device_type }}",
        "proxy_host": "{{ proxy_host }}",
        "proxy_port": "{{ proxy_port }}"
        }'
    when: proxy_host is defined and proxy_port is defined
  - name: Claim devices
    # Intersight API keys provided by settings_file variable
    # ----------
    script: claim_device.py -f "{{ settings_file }}" -j ' {{ stash_json }}'
    register: result
    changed_when: '"true" in result.stdout'
