---

- hosts: ucs
  connection: local
  gather_facts: no
  vars:
    # override on command line if needed
    api_params_file: intersight_api_params.json
  environment:
    PYTHONPATH: "{{ playbook_dir }}"
  tasks:
  # default values that can be overridden in inventory
  - name: Default to no proxy settings
    set_fact:
      proxy_host: ''
      proxy_port: 0
    when: proxy_host is not defined or proxy_port is not defined
  - name: Default access mode to allow control (read-only false)
    set_fact:
      read_only: false
    when: read_only is not defined
  - name: Define JSON string passed to claim script
    set_fact:
      # JSON for each host being claimed.
      # Quotes and whitespace are importantant for the JSON string passed to claim script.
      # ----------
      stash_json: ' { "hostname": "{{ hostname }}",
        "username": "{{ username }}",
        "password": "{{ password }}",
        "device_type": "{{ device_type }}",
        "proxy_host": "{{ proxy_host }}",
        "proxy_port": "{{ proxy_port }}",
        "read_only": "{{ read_only }}"
        }'
  - name: Claim devices
    script: claim_device.py -a "{{ api_params_file }}" -d ' [{{ stash_json }}]'
    register: result
    changed_when: '"true" in result.stdout'
